export const contractOnlyRuntimeQuestions = [
  "flowTest.app can seed ResourceStore snapshots, but live resource lookup execution is still partial.",
  "flow.transaction is the target name; executable examples use flow.mutation until the runtime grows the alias.",
  "Transaction params and commit are target names; runtime configs still adapt through input and effect.",
  "Stream sources use subscribe adapters; unsubscribe/dispose cleanup receipts remain contract-only.",
  "State-scoped stream fibers, virtual time, and bounded settle remain contract-only.",
] as const;

export const launchApiCoverage = [
  ["flow.module", "screen modules"],
  ["flow.resource", "runtime-owned data"],
  ["flow.transaction", "project save and approval target"],
  ["flow.mutation", "transaction compatibility descriptor"],
  ["flow.machine", "screen workflows"],
  ["flow.view", "render projections"],
  ["flow.app", "module composition"],
  ["App.layer", "Effect layer composition"],
  ["flow.runtime", "managed runtime entry"],
  ["flow.ensure", "load resource before state"],
  ["flow.observe", "visible resource subscription"],
  ["flow.refresh", "explicit resource refresh"],
  ["flow.run", "transaction commit compatibility descriptor"],
  ["flow.patch", "preview resource patch"],
  ["flow.invalidate", "cache invalidation"],
  ["flow.stream", "subscribe-backed upload/chat/assistant streams"],
  ["flow.after", "dismiss timers"],
  ["flow.child", "assistant task ownership"],
  ["flow.can", "command availability"],
  ["flow.useResource", "React resource read"],
  ["flow.use", "React actor read"],
  ["flow.useView", "React projection read"],
  ["flowTest", "scenario tests"],
  ["flowTest.app", "future app harness"],
  ["createControlledEffect", "service test utility"],
  ["createControlledStream", "stream test utility"],
] as const;
