export const contractOnlyRuntimeQuestions = [
  "flow.runtime(AppLayer) exposes ResourceStore seed/get/patch/subscribe and OrchestratorSystem handles; full live lookup, freshness, and deterministic scheduler semantics remain partial.",
  "Module metadata, app inventory, dependency validation, cycle validation, and duplicate resource-id validation are executable; static resource-tag validation remains contract-only.",
  "flow.transaction is executable through the current transaction runner; user-facing receipt labels are still pending.",
  "Offline transaction queue, undo rollback, and replay receipts are parked as future work outside the core rebuild.",
  "Transaction params and commit are executable target names; params schema validation remains contract-only.",
  "Chat actor unsubscribe/dispose cleanup, STOP_GENERATION interrupt, stream subscribe authoring, and stream generation snapshots are executable.",
  "Assistant child actors, child stop receipts, child failure bubbling, and retry-only-failed-child supervision are executable; automatic restart policies remain contract-only.",
  "Virtual time, deterministic mailboxes, and bounded settle remain contract-only.",
] as const;

export const launchApiCoverage = [
  ["flow.module", "screen modules"],
  ["flow.resource", "runtime-owned data"],
  ["flow.transaction", "project save and approval descriptors"],
  ["flow.machine", "screen workflows"],
  ["flow.view", "render projections"],
  ["flow.app", "module composition"],
  ["App.layer", "Effect layer composition"],
  ["flow.runtime", "managed runtime and orchestrator entry"],
  ["flow.ensure", "load resource before state"],
  ["flow.observe", "visible resource subscription"],
  ["flow.refresh", "explicit resource refresh"],
  ["flow.run", "transaction commit compatibility descriptor"],
  ["flow.patch", "preview resource patch"],
  ["flow.invalidate", "cache invalidation"],
  ["flow.stream", "subscribe-backed upload/chat/assistant streams with generation snapshots"],
  ["flow.after", "dismiss timers"],
  ["flow.child", "assistant task ownership"],
  ["flow.can", "command availability"],
  ["flow.useResource", "React resource read"],
  ["flow.use", "React actor read"],
  ["flow.useView", "React projection read"],
  ["flowTest", "scenario tests"],
  ["flowTest.app", "seeded app harness"],
  ["createControlledEffect", "service test utility"],
  ["createControlledStream", "stream test utility"],
] as const;
